# fly.toml app configuration file generated for fastapi-development on 2023-08-27T19:54:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fastapi-development"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
