name: Deploy to Docker Hub
on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.vscode"

  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.vscode"

  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

  workflow_dispatch: # Allow manual invocation of the workflow

jobs:
  deploy-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fcc-fastapi:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fcc-fastapi:latest
          cache-to: type=inline

      - run: echo "🍏 This job's status is ${{ job.status }}."
